// Save the currently set options to an ini file.

var filename = prefix_project_path_if_needed('config.ini')
FS_ini_open(filename)
FS_ini_write_real('prefs','death',global.deathEnabled)
FS_ini_write_real('prefs','speed',room_speed)
FS_ini_write_real('prefs','gridsnap',oEdit.snap)
FS_ini_write_string('prefs','skin',global.skinName)
FS_ini_write_real('prefs','fullscreen',window_get_fullscreen())
FS_ini_write_real('prefs','showanalysis',global.showanalysis)
FS_ini_write_real('prefs','dotkidoutline',global.dotkidoutline)
FS_ini_write_real('prefs','hidesidebar',global.hidesidebar)
FS_ini_write_real('prefs','editorinstructions',global.editorinstructions)
FS_ini_write_real('prefs','showhitbox',global.showhitbox)
FS_ini_write_real('prefs','showgrid',global.showgrid)
FS_ini_write_real('prefs','playery_extended',global.playery_extended)
FS_ini_close()
